### ISSUE TITLE
Fix problem with commit lint

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#757] opened 2024-06-03 12:08 UTC
**What**

There is an intermittent problem with the commitlint configuration that has been reported by @pazbardanl @jmcook1186 and @manushak but does not yet have a diagnosis. It needs diagnoising and fixing to ensure we maintain a good developer experience.

**Why**
As a developer I want to be able to raise PRs into IF without having to fiddle with commitlint config as it degrdaes the DX.

**Context**

When developing locally, there are cases where `npm test` reports 100% passing tests and `npm run fix` reports no issues, however, when pushing a commit, commitlint errors out due to failing tests. Removing `npm test` from the commitlint config solves the issue, suggesting that there is some difference between the true state of the local environment and the one commitlint is using to run its tests.

**SoW**

- [ ] diagnose problem with commitlint tests
- [ ] fix issue across all IF repositories

**Acceptance criteria**

- [ ] issue is fixed
GIVEN the issue is fixed and my local repository passes `npm test` and I have run `npm run fix`
WHEN I push new commits from my remote copy of IF
THEN commitlint should not reject the changes

**Comment by zanete** [comment] 2024-06-03 12:08
@jmcook1186 please report the issue that you have experienced when you can't push your commits

**Comment by narekhovhannisyan** [comment] 2024-06-06 16:12
@jmcook1186 do you know any steps to reproduce this?

**Comment by jmcook1186** [comment] 2024-06-07 10:02
I'm not sure, I'm afraid, it occurs frequently but I haven't yet noticed what the pattern is. At some point during development commits just stop passing commitlint due to test failures. Speculate that maybe it happens after a git pull when there are staged local changes, but not sure that this is true.

**Comment by zanete** [comment] 2024-06-10 12:05
@manushak @jmcook1186 please add any context you can when you experience this issue as it is currently not possible for @narekhovhannisyan to replicate

**Comment by jmcook1186** [comment] 2024-06-11 15:03
@manushak and @narekhovhannisyan to have sync to identify cause

**Comment by jmcook1186** [comment] 2024-07-09 14:46
Closing as it seems to have fixed itself in the interim...!

**Closed by jmcook1186** 2024-07-09 14:46 UTC
Labels: bug, core-only
