### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by DimaRadionov** [Green-Software-Foundation/if#739] opened 2024-05-27 07:20 UTC
I wanted to run a manifest file and received an error: Cannot convert undefined or null to object. 
## Description of the Error

I was developing a tool, which will track the co2 emmisions. When it all cames to run the manifest file, I received an error. 
## Expected Behaviour

Should run, cause I copied a simple manifest file 
## Actual Behaviour

error:     Cannot convert undefined or null to object
## Manifest File That Generated the Error

name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20
## Runtime Info

[2024-05-27 09:05:51.402 AM] error:     Cannot convert undefined or null to object
TypeError:      Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at listDependencies (C:\Users\e-doiv\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\environment.js:42:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async injectEnvironment (C:\Users\e-doiv\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\environment.js:49:26)
    at async impactEngine (C:\Users\e-doiv\AppData\Roaming\npm\node_modules\@grnsft\if\build\index.js:22:25)

**Comment by jmcook1186** [comment] 2024-05-28 08:50
Hi - sorry but I can't reproduce your error. You pasted the yaml flat, so I can't check whether the indentation was correct. This is how I ran your yaml data in my local IF and it executed fine.

```yaml
name: basic-demo
description:
tags:
initialize:
  plugins:
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20

```

**Comment by jmcook1186** [comment] 2024-05-31 09:44
Closing this out as I don't think there;s anything that needs fixing. Please feel free to reach out again as needed.

**Closed by jmcook1186** 2024-05-31 09:44 UTC
Labels: bug

**Comment by adamaucamp** [comment] 2024-06-03 09:43
I also encounter this issue withe npm installed version of the IF project. 
It does not occur if you clone the if repo from source and build it yourself however. 


```
[2024-06-03 11:17:45.622 AM] error:     Cannot convert undefined or null to object
TypeError:      Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at listDependencies (/opt/homebrew/lib/node_modules/@grnsft/if/build/lib/environment.js:42:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async injectEnvironment (/opt/homebrew/lib/node_modules/@grnsft/if/build/lib/environment.js:49:26)
    at async impactEngine (/opt/homebrew/lib/node_modules/@grnsft/if/build/index.js:22:25)
```

It seems to have something to do with the dependency list thats happening in the src/lib/environment.ts file:

```js
/**
 * 1. Runs `npm list --json`.
 * 2. Parses json data and converts to list.
 */
const listDependencies = async () => {
  const {stdout} = await execPromise('npm list --json');
  const npmListResponse: NpmListResponse = JSON.parse(stdout);
  const dependencies = Object.entries(npmListResponse.dependencies);

  return flattenDependencies(dependencies);
};
```


`npm list --json` returns an empty object `{}` if there is no package.json in the folder its being run in. so it returns an empty/null object when ie is run outside of an npm project... 

You can replicate the issue with the source code version if you simply run it from one directory up that does not have a package.json file.
eg:

```sh
node ./if/build/index.js --manifest if/manifests/examples/basic.yml --output out.tmp
```

so maybe we just need to modify 

```js
const dependencies = Object.entries(npmListResponse.dependencies);
```
to be ok if `dependencies` is null?


Also on further investigation, this breaks completely if the directory you run `ie' in contains a package.json that has not been initialised. It also seems like this logic implies that ie will believe and report that only the packages referenced in the local package.json is relevant and will be published to the output? 

example error

```
Error:  Command failed: npm list --json
npm error code ELSPROBLEMS
npm error missing: @commitlint/cli@^18.6.0, required by k8s-container-carbon@1.0.0
npm error missing: @commitlint/config-conventional@^18.6.0, required by k8s-container-carbon@1.0.0
npm error missing: @grnsft/if-unofficial-plugins@^0.3.1, required by k8s-container-carbon@1.0.0
npm error missing: csv-stringify@^6.4.6, required by k8s-container-carbon@1.0.0
npm error missing: js-yaml@^4.1.0, required by k8s-container-carbon@1.0.0
npm error missing: luxon@^3.4.4, required by k8s-container-carbon@1.0.0
```

this happens with the basic yaml from the example above. the package.json in question has absolutely nothing to do with the execution, yet ie seems to want to parse it and use it as "dependency reference".

**Comment by adamaucamp** [comment] 2024-06-03 09:55
We can fix the package.json absent issue with

```js
  const dependencies = Object.entries(npmListResponse.dependencies ?? {});
```

Don't know about the  \
``` 
"error": {
    "code": "ELSPROBLEMS",
    "summary": "missing: 
```

error, may have to look at the intent behind the logic, i'm sure the point is to put in all the dependencies used during execution and not just publish whatever happens to be in the local package.json...
