### ISSUE TITLE
Identify bultins with node-level config

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#775] opened 2024-06-05 13:52 UTC
**Why**: Sub of #765 
**What**: built in audit to identify all the cases where node-level config is used #775

**Scope of work:**
- [ ] a list of built-ins that use node-level config

**Comment by jmcook1186** [comment] 2024-06-07 08:32
closing as duplicate of #776

**Closed by jmcook1186** 2024-06-07 08:32 UTC
Labels: draft
