### ISSUE TITLE
Revise issue refinement/readiness process

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/if#613] opened 2024-04-10 12:36 UTC
Sub of #651 

## User story
As a core developer I want to treat issues consistently and make sure I know what changes are required to close a ticket in advance of working on it. I also want to be able to spec tickets sufficiently so that community contributors can work on them with clarity and with unambiguous expectations.

## Rationale
We currently work on issues based on internal conversations or loose specifications, and sometimes we are guilty of defining the task while it is in flight. This doesn't serve the community very well as it is a barrier to contributing effectively, and it has also led to miscommunications within the team. Therefore, we should inspect our processes and devise something better.

## Implementation details
- [x] examine current process
- [x] propose changes, probably including a revised issue template
- [ ] document issue readiness criteria
- [ ] establish any additional team calls, calendar events or other scheduling we need to ensure tickets get refined

## Priority
4/5

## Size
M

## What does "done" look like?
Process updated, documented and implemented

## Deadline
tbc

**Comment by jmcook1186** [comment] 2024-04-11 13:06
Hi @narekhovhannisyan @manushak @MariamKhalatova @jawache @pazbardanl here is a suggestion for a ticket refinement/readiness process to implement across IF repositories. Please use this as a starting point for discussions and provide feedback in comments here!

## Refinement

Refinement is the process of taking a loosely scoped or ambiguous ticket and making it so well-described that anyone could pick it up off the board and produce an equivalent outcome to one of the core team. It's important we do this diligently even if it feels unnecessary or frictionful, because:

- it keeps us all aligned with the purpose and rationale of individual tasks
- it improves our transparency
- it lowers the barrier to entry for contributors
- it helps us to "measure twice, cut once" and avoid doing work more than once
- it helps us to think together about each issue
- it provides an archive of our thinking that we can go back to in future.

We can make the refinement process as consistent as possible by sticking faithfully to issue templates. By choosing the fields carefully and filling them out thoroughly, we can ensure the right information is available, and using checkboxes for subtask will help us to track progress and be precise about the scope of the ticket.

## Peer-review

We will also implement a mini peer-review process for each ticket, where a team member is required to review a ticket and make it READY - we should not typically make our own tickets READY. Instead, when you create a ticket, you assign another team member to be the reviewer. Then, responsibility for the thoroughness of the information is shared and we can hold each other accountable.

The reviewer can add the `READY` label when they are satisfied with the ticket quality.

## Suggested Issue Content

- **rationale/context:** why is this change required, what are the intended outcomes
- **what does done look like**: a list of checkboxes enumerating specific outcomes that can be ticked off when complete
- **size**: how long will this take (t-shirt sizing ok)
- **prerequisites/resources** : does anything else need to happen to enable this work to be completed?
- **implementation details**: what specific steps will be taken to address the aims of the ticket?
- **updates to documentation**: enumerate specific changes required to the documentation, formatted as checkboxes with associated urls
- **assignment**: who should work on this ticket
- **labels**: label appropriately, including one label from each of the following types: type, size, urgency, status
- **what testing is required**: what tests are required for the changes to get merged?
- **reviewer**: assign a reviewer who can make this ticket READY

for issues relating to features/plugins:
- **manifest**: provide a draft manifest that should run when this task is completed

## Refinement calls

We can do ticket refinement any time and it is possible to refine a ticket entirely async. However, I plan to add a weekly refinement session to the calendar where we can focus on refinement tasks together. 

## When is a ticket READY?

Triaged by core team (can be async discussion, spike call, triage call or sprint planning discussion)
All necessary fields are completed
Reviewer has added `READY` label

These things need to have happened before a ticket can be worked on

**Comment by jawache** [comment] 2024-04-16 15:00
@jmcook1186 I think what we need here is a broader document that details the internal development process, the creation of that document with cement the process and the PR to document that process is the place where the team can put in comments and their thoughts.

**Acceptance Criteria**
- [ ] Updated issue template adhering to the GSF PM protocol.
- [ ] Updated documentation regarding what our process is for defining, refining and prioritizing work.
- A PR to a doc `/if/something.md` which details the internal process.
- Explanation of the different fields in in the issue template.
- Explanation of the different columns in the project board (and any custom fields) and the minimum requirements for moving from one column to the next.
- The process for deciding what issues to pick for each sprint.
- How we decide an issue is ready to be worked on and what is the process for getting an issue ready to work on

I'm not sure what the exact answers to the above questions are but if you create a PR to document the process that seems to be the right place to start, you propose something, the team (and I) will weigh in and discuss in the PR.

**Comment by pazbardanl** [comment] 2024-04-17 10:37
@jmcook1186 @jawache  If I understand correctly, what you're describing resembles Story Grooming, where a user story or issue is refined to a state where anyone can pick it up and work on it to completion with minimal follow-up questions. 
Typically, this responsibility falls on a single person, often the Product Owner, in an ideal scenario.

However, considering the collaborative nature of our core team, I think it might be feasible to have everyone on the core team involved in refining/grooming each other's issues. 
However, i do think an MVP approach could be beneficial:

1. Start by designating specific issues to be groomed, keeping the initial changes to a smaller scale (and keeping the rest as "control group", read on...)
2. Define a limited set of items to be fleshed out during refinement/grooming, such as **high-level implementation steps**, the **Definition of Done** (DoD), **acceptance criteria** (which differs subtly from DoD), and **dependencies**. The inclusion of **estimation** and **assignee** can be debated, as some prefer to determine these details during sprint planning while others prefer to have them predefined for efficiency and workload balancing.
3. Set a defined period, perhaps 1 or 2 sprints, to engage in discussions (either sync or async) on each groomed/ready story. This will help us understand how do **WE, collectively** envision ideal grooming, considering the unique nature of our project (open-source, distributed, etc.).
4. Evaluate the impact of grooming by comparing the experience of working on groomed/ready issues with those that didn't undergo this process. This "control group" approach will provide insights into how effective the refining/grooming process actually is. Ideally, it will validate its efficacy and prompt its application to other issues. In the worst-case scenario, it will lead to refinement and improvement of the process.

WDYT?

**Comment by jawache** [comment] 2024-04-17 21:25
Thanks @pazbardanl , good insights. 

The approach we landed on in a discussion today was to have a two step process.

Design then Refine.

In design @jmcook1186 and I (the "product owners", are you interested in designing?) will detail the what, why, context and acceptance criteria using them given, when, then syntax so there is clear direction regarding each ticket.

Then the team/assignee can refine the ticket, add implementation steps, testing, documentation, estimation etc ...

There is just a lot of room left for interpretation and refinement without that clear direction risks leading to a lot of rework.

**Comment by jmcook1186** [comment] 2024-04-18 13:32
OK - to summarize the latest state of the conversation:

1) ticket is proposed in draft form using the `dev-ticket` template
2) @jawache and @jmcook1186 refine the ticket with focus on the context and acceptance criteria
  - acceptance criteria in given-when-then format to be used as a design spec
3) ticket is assigned to a developer, who refines the scope of work and size
4) issue is signed off  (indicated with the `READY` label) and work can begin
5) any interim discussions happen in comments on the issue
6) developer raises PR linked to issue
7) PR gets reviewed and merged after 2 approvals
8) ticket closed when PR is merged

@jawache @pazbardanl

**Comment by zanete** [comment] 2024-04-25 15:38
@zanete to put some docs around the workflow

**Comment by zanete** [comment] 2024-05-08 09:28
@jmcook1186 as discussed, I've started to document the workflow, boards and the issue anatomy in a separate notions page: https://www.notion.so/grnsft/IF-Core-Team-Development-Practice-fe091d3963644499857238d49e9fa802?pvs=4
I will continue refining it over next week, too, and look fowrard to your feedback and input.
cc @jawache

**Closed** 2024-06-12 10:53 UTC
