### ISSUE TITLE
Make `TimeSync` a builtin feature

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/if#823] opened 2024-06-11 20:09 UTC
**Why**: Sub of #763 
**What**: Move `TimeSync` so it is a builtin feature like `aggregate` rather than a plug in in `builtins`

Blocked by:
- #809 
- #822 

**Scope of work:**
- [ ] TBC

**Comment by jmcook1186** [comment] 2024-06-17 14:13
Closing as duplicate of #822

**Closed by jmcook1186** 2024-06-17 14:13 UTC
Labels: blocked, draft, core-only
