### ISSUE TITLE
Dev ticket - Can not resolve SciModel

### ISSUE THREAD

**Issue by Irenia111** [Green-Software-Foundation/if#414] opened 2024-01-29 05:45 UTC
I have tried to use IF cli with the example yaml. But I kept receiving error messages as the snapshot until I deleted the SciModel config in the `graph.children.child.config.sci`. 

It's so weird since my colleague can resolve the same yaml file with the IF cli and we both use the node v18.17.1 (npm v9.6.7).

<img width="1255" alt="Screenshot 2024-01-29 at 13 32 35" src="https://github.com/Green-Software-Foundation/if/assets/52985516/d6f97df8-8827-4b6d-a914-85fa5c423acb">

**Comment by jmcook1186** [comment] 2024-01-29 09:01
closing this as it seems to be a duplicate of #415 - we can discuss there

**Closed by jmcook1186** 2024-01-29 09:01 UTC
